### ISSUE TITLE
Release new version without ActiveSupport dependency

### ISSUE THREAD

**Issue by bglusman** [kamilc/email_verifier#28]
I was so confused playing with this locally why it was erroring without active support!  I looked at the code and saw you were checking if it was defined, and it all looked good, and finally I realized that was done in latest commit and not part of the 0.9 release!  Please release the updated version, I might build a gem including this, a Gemfile can point straight at github but another gem can't unless it's published.

**Comment by kamilc** [comment]
The new version 0.1.0 has just been publish. Apologies for the delay.
